#ifndef __BIO_DEFS__
#define __BIO_DEFS__

#include <stdio.h>

enum //ICAO_ERROR
{
    ICAO_ERROR_NO_ERROR = 0,

    ICAO_ERROR_TRANSMIT_PLAIN_APDU,
    ICAO_ERROR_TRANSMIT_PLAIN_APDU_RESP,

    ICAO_ERROR_TRANSMIT_SECURE_APDU,
    ICAO_ERROR_TRANSMIT_SECURE_APDU_DO87_ENC,
    ICAO_ERROR_TRANSMIT_SECURE_APDU_DO8E_MAC,
    ICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO99,
    ICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO8E,
    ICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO8E_MAC,
    ICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO8E_MAC_MISMATCH,
    ICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO87_DENC,

    ICAO_ERROR_GETMAC_ENCRYPT,
    ICAO_ERROR_GETMAC_DECRYPT,

    ICAO_ERROR_UPDATEKEY_GETDOCBARCODE,
    ICAO_ERROR_UPDATEKEY_GETDOCTYPE,
    ICAO_ERROR_UPDATEKEY_INVALID_DOCTYPE,
    ICAO_ERROR_UPDATEKEY_GETDOCSERIAL,
    ICAO_ERROR_UPDATEKEY_DOCSERIAL_UNAVAILABLE,
    ICAO_ERROR_UPDATEKEY_GETDOCBIRTHDATE,
    ICAO_ERROR_UPDATEKEY_DOCBIRTHDATE_UNAVAILABLE,
    ICAO_ERROR_UPDATEKEY_GETDOCEXPIRYDATE,
    ICAO_ERROR_UPDATEKEY_DOCEXPIRYDATE_UNAVAILABLE,

    ICAO_ERROR_AUTHENTICATE,
    ICAO_ERROR_AUTHENTICATE_RESP,

    ICAO_ERROR_UPDATEICAORESULTS_PUTDATA_DOC_BIRTHDATE,
    ICAO_ERROR_AUTHENTICATE_KSEED_HASH,
    ICAO_ERROR_AUTHENTICATE_KENC_HASH,
    ICAO_ERROR_AUTHENTICATE_KMAC_HASH,
    ICAO_ERROR_AUTHENTICATE_LOCAL_CHALLENGE,
    ICAO_ERROR_AUTHENTICATE_LOCAL_RAND,
    ICAO_ERROR_AUTHENTICATE_AUTH_DATA_ENC,
    ICAO_ERROR_AUTHENTICATE_AUTH_DATA_MAC,
    ICAO_ERROR_AUTHENTICATE_RESP_LEN,
    ICAO_ERROR_AUTHENTICATE_RESP_DATA_MAC,
    ICAO_ERROR_AUTHENTICATE_RESP_MAC_VERIFICATION,
    ICAO_ERROR_AUTHENTICATE_RESP_DATA_ENC,
    ICAO_ERROR_AUTHENTICATE_RESP_SCARD_CHALLENGE_VERIFICATION,
    ICAO_ERROR_AUTHENTICATE_RESP_LOCAL_CHALLENGE_VERIFICATION,


    ICAO_ERROR_UPDATEICAORESULTS_DATAFIELD_INALID,
    ICAO_ERROR_CONNETC_SELECT_DIR,
    ICAO_ERROR_CONNETC_SELECT_DIR_RESP,

    ICAO_ERROR_GETFINGERREF_PUTDATA_FINGER1,
    ICAO_ERROR_GETDOCUMENTNUMBER_SELECT_APP,
    ICAO_ERROR_GETDOCUMENTNUMBER_SELECT_APP_RESP,
    ICAO_ERROR_GETDOCUMENTNUMBER_SELECT_MF,
    ICAO_ERROR_GETDOCUMENTNUMBER_SELECT_MF_RESP,
    ICAO_ERROR_GETDOCUMENTNUMBER_SELECT,
    ICAO_ERROR_GETDOCUMENTNUMBER_SELECT_RESP,
    ICAO_ERROR_GETDOCUMENTNUMBER_READ,
    ICAO_ERROR_GETDOCUMENTNUMBER_READ_RESP,


    ICAO_ERROR_CONNETC_WRAP,
    ICAO_ERROR_CONNETC_READ_BIN,
    ICAO_ERROR_CONNETC_READ_BIN_RESP,
    ICAO_ERROR_CONNETC_PACE_SEC_NEW,
    ICAO_ERROR_CONNETC_EAC_INIT_CTX,
    ICAO_ERROR_CONNETC_PACE_STEP2,
    ICAO_ERROR_CONNETC_PACE_STEP3A,
    ICAO_ERROR_CONNETC_UNWRAP,
    ICAO_ERROR_CONNETC_PACE_STEP3A_MAP,
    ICAO_ERROR_CONNETC_PACE_STEP3B,
    ICAO_ERROR_CONNETC_BUFF_MEM_INIT,
    ICAO_ERROR_CONNETC_PACE_STEP3C,
    ICAO_ERROR_CONNETC_PACE_STEP3D,
    ICAO_ERROR_CONNETC_PACE_STEP3D_VERIF,
    ICAO_ERROR_CONNETC_EAC_SET_CTX,
    ICAO_ERROR_GETFINGERREF_SELECT_APP,
    ICAO_ERROR_GETFINGERREF_SELECT_APP_RESP,
    ICAO_ERROR_GETICAO_SELECT_APP,
    ICAO_ERROR_GETICAO_SELECT_APP_RESP,
    ICAO_ERROR_GETICAO_GETCHALLENGE,
    ICAO_ERROR_GETICAO_GETCHALLENGE_RESP,
    ICAO_ERROR_GETICAO_GETCHALLENGE_RESP_LEN,
    ICAO_ERROR_GETICAO_AUTHENTICATE,
    ICAO_ERROR_GETICAO_SELECTDG,
    ICAO_ERROR_GETICAO_SELECTDG_RESP,
    ICAO_ERROR_GETICAO_READDG,
    ICAO_ERROR_GETICAO_READDG_RESP,
    ICAO_ERROR_GETICAO_READDG_RESP_LEN,
    ICAO_ERROR_GETICAO_READDG_OVERFLOW,
    ICAO_ERROR_GETFINGERREF_GETDATA1,
    ICAO_ERROR_GETFINGERREF_GETDATA1_RESP,
    ICAO_ERROR_GETFINGERREF_PUTDATA_FINGER2,
    ICAO_ERROR_GETDOCUMENTNUMBER_PUTDATA_DOC_SERIAL,
    ICAO_ERROR_INIT_ENGINEHANDLE_MEM,
    ICAO_ERROR_CREATE_MUTEX,

    ICAO_ERROR_ADDCAPTUREFIELD_DATAFIELD_INALID,
    ICAO_ERROR_CAPTURE_DEVICEHANDLE_NULL,

ICAO_ERROR_CAPTURE_GETCARD,
ICAO_ERROR_CAPTURE_DISCONNECT,
ICAO_ERROR_MOC_DEVICEHANDLE_NULL,
ICAO_ERROR_MOC_FINGER_REF_INVALID,
ICAO_ERROR_MOC_GET_TEMPLATE,
ICAO_ERROR_NO_CARD_AVAILABLE,
ICAO_ERROR_MOC_GETCARD,
ICAO_ERROR_MOC_SELECT_APP_RESP,
ICAO_ERROR_MOC_MATCH,
ICAO_ERROR_MOC_SELECT_APP,
ICAO_ERROR_MOC_MATCH_P1,
ICAO_ERROR_MOC_MATCH_WRONG_LENGTH,
ICAO_ERROR_MOC_MATCH_PIN_NOT_FOUND,
ICAO_ERROR_MOC_MATCH_SECURITY,
ICAO_ERROR_MOC_MATCH_COUNTER_ZERO,
ICAO_ERROR_MOC_MATCH_NEED_MORE_DATA,
ICAO_ERROR_MOC_MATCH_UNKNOWN,
ICAO_ERROR_MOC_DISCONNECT,




};

enum // BIO_DATAFIELD
{
    BIO_MOC_HIT = 0,
    BIO_MOC_NOHIT
};



enum // BIO_DATAFIELD
{
    BIO_DATAFIELD_DOC_BARCODE = 0,
    BIO_DATAFIELD_DOC_TYPE,
    BIO_DATAFIELD_DOC_SERIAL,
    BIO_DATAFIELD_DOC_BIRTHDATE,
    BIO_DATAFIELD_DOC_EXPIRYDATE,
    BIO_DATAFIELD_DOC_RUN,
    BIO_DATAFIELD_DOC_NAMES,
    BIO_DATAFIELD_DOC_SURNAME_1,
    BIO_DATAFIELD_DOC_SURNAME_2,
    BIO_DATAFIELD_DOC_GENDER,

    BIO_DATAFIELD_DOC_NATIONALITY,
    BIO_DATAFIELD_DOC_MRZ,
    BIO_DATAFIELD_DOC_COUNTRY_OF_ISSUE,
    BIO_DATAFIELD_DOC_OCUPATION,
    BIO_DATAFIELD_DOC_BIRTHPLACE,
    BIO_DATAFIELD_DOC_ISSUEDATE,

    BIO_DATAFIELD_DOC_FACE,
    BIO_DATAFIELD_DOC_SIGNATURE,

    BIO_DATAFIELD_DOC_FINGERID_1,
    BIO_DATAFIELD_DOC_FINGERID_2,
    BIO_DATAFIELD_DOC_FINGERID_1_TRIES_LEFT,
    BIO_DATAFIELD_DOC_FINGERID_2_TRIES_LEFT,

    BIO_DATAFIELD_DOC_DG_COM,
    BIO_DATAFIELD_DOC_DG_1,
    BIO_DATAFIELD_DOC_DG_2,
    BIO_DATAFIELD_DOC_DG_3,
    BIO_DATAFIELD_DOC_DG_4,
    BIO_DATAFIELD_DOC_DG_5,
    BIO_DATAFIELD_DOC_DG_6,
    BIO_DATAFIELD_DOC_DG_7,
    BIO_DATAFIELD_DOC_DG_8,
    BIO_DATAFIELD_DOC_DG_9,
    BIO_DATAFIELD_DOC_DG_10,
    BIO_DATAFIELD_DOC_DG_11,
    BIO_DATAFIELD_DOC_DG_12,
    BIO_DATAFIELD_DOC_DG_13,
    BIO_DATAFIELD_DOC_DG_14,
    BIO_DATAFIELD_DOC_DG_15,

    BIO_DATAFIELDPROP_NONE,

    BIO_DATAFIELDPROP_IMAGEFORMAT_SOLJP2,

    BIO_DATAFIELDPROP_MINUTIAE_SOLISOC,
};

enum {

    BIO_FINGER_NONE = 0
};


enum {
    SCL_FNBITMAP_ON = 0
};


enum {
    BIO_ERROR_NO_ERROR = 0,
    BIO_ERROR_NO_DATA_AVAILABLE,
    BIO_ERROR_LICENSE_FNBITMAP_OFF,
    BIO_ERROR_MOC_LOCKED
};


enum {
    BIO_DOCTYPE_CLID2013 = 0,
    BIO_DOCTYPE_CLID2013_ESP,
    BIO_FEATUREBITMAP_CAPT_ICAO_DATA,
    BIO_FEATUREBITMAP_CAPT_ICAO_FACE,
    BIO_FEATUREBITMAP_CAPT_ICAO_SIGNATURE,
    BIO_FEATUREBITMAP_CAPT_ICAO_DOCNUM,
    BIO_FEATUREBITMAP_CAPT_ICAO_FINGER,
    BIO_FEATUREBITMAP_CAPT_ICAO_DATAGROUP
    
};

enum {
    BIO_DEVICE_BIOPIN = 0,
    BIO_DEVICE_BCR250BT,
    BIO_DEVICE_NFC
};


enum {
    SMARTCARD_ERROR_NO_ERROR = 0,
    SMARTCARD_ERROR_NO_CARD_AVAILABLE
};


// enum  enDataField
// {
//     SMARTCARD_ERROR_NO_ERROR = 0,
//     SMARTCARD_ERROR_NO_CARD_AVAILABLE
// };







// #ifndef __ENUMS_H__
// #define __ENUMS_H__

// /* ============================================================
// ICAO - ERRORES
// ============================================================ */

// enum ICAO_ERROR
// {
// ICAO_ERROR_NO_ERROR = 0,

// ```
// /* Plain APDU */
// ICAO_ERROR_TRANSMIT_PLAIN_APDU,
// ICAO_ERROR_TRANSMIT_PLAIN_APDU_RESP,

// /* Secure APDU */
// ICAO_ERROR_TRANSMIT_SECURE_APDU,
// ICAO_ERROR_TRANSMIT_SECURE_APDU_DO87_ENC,
// ICAO_ERROR_TRANSMIT_SECURE_APDU_DO8E_MAC,
// ICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO99,
// ICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO8E,
// ICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO8E_MAC,
// ICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO8E_MAC_MISMATCH,
// ICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO87_DENC,

// /* MAC / Crypto */
// ICAO_ERROR_GETMAC_ENCRYPT,
// ICAO_ERROR_GETMAC_DECRYPT,

// /* Update ICAO Key */
// ICAO_ERROR_UPDATEKEY_GETDOCBARCODE,
// ICAO_ERROR_UPDATEKEY_GETDOCTYPE,
// ICAO_ERROR_UPDATEKEY_INVALID_DOCTYPE,
// ICAO_ERROR_UPDATEKEY_GETDOCSERIAL,
// ICAO_ERROR_UPDATEKEY_DOCSERIAL_UNAVAILABLE,
// ICAO_ERROR_UPDATEKEY_GETDOCBIRTHDATE,
// ICAO_ERROR_UPDATEKEY_DOCBIRTHDATE_UNAVAILABLE,
// ICAO_ERROR_UPDATEKEY_GETDOCEXPIRYDATE,
// ICAO_ERROR_UPDATEKEY_DOCEXPIRYDATE_UNAVAILABLE,

// /* Update ICAO Results */
// ICAO_ERROR_UPDATEICAORESULTS_PUTDATA_DOC_BIRTHDATE,
// ICAO_ERROR_UPDATEICAORESULTS_DATAFIELD_INALID,

// /* Authentication */
// ICAO_ERROR_AUTHENTICATE_KSEED_HASH,
// ICAO_ERROR_AUTHENTICATE_KENC_HASH,
// ICAO_ERROR_AUTHENTICATE_KMAC_HASH,
// ICAO_ERROR_AUTHENTICATE_LOCAL_CHALLENGE,
// ICAO_ERROR_AUTHENTICATE_LOCAL_RAND,
// ICAO_ERROR_AUTHENTICATE_AUTH_DATA_ENC,
// ICAO_ERROR_AUTHENTICATE_AUTH_DATA_MAC,
// ICAO_ERROR_AUTHENTICATE,
// ICAO_ERROR_AUTHENTICATE_RESP,
// ICAO_ERROR_AUTHENTICATE_RESP_LEN,
// ICAO_ERROR_AUTHENTICATE_RESP_DATA_MAC,
// ICAO_ERROR_AUTHENTICATE_RESP_MAC_VERIFICATION,
// ICAO_ERROR_AUTHENTICATE_RESP_DATA_ENC,
// ICAO_ERROR_AUTHENTICATE_RESP_SCARD_CHALLENGE_VERIFICATION,
// ICAO_ERROR_AUTHENTICATE_RESP_LOCAL_CHALLENGE_VERIFICATION,

// /* Connect / NFC */
// ICAO_ERROR_CONNETC_SELECT_DIR,
// ICAO_ERROR_CONNETC_SELECT_DIR_RESP,
// ICAO_ERROR_CONNETC_WRAP,
// ICAO_ERROR_CONNETC_READ_BIN
// ```

// };

// /* ============================================================
// BIO - DATA FIELDS (COMPLETO)
// ============================================================ */

// enum BIO_DATAFIELD
// {
// /* Básicos */
// BIO_DATAFIELD_DOC_BARCODE = 0,
// BIO_DATAFIELD_DOC_TYPE,
// BIO_DATAFIELD_DOC_SERIAL,
// BIO_DATAFIELD_DOC_BIRTHDATE,
// BIO_DATAFIELD_DOC_EXPIRYDATE,
// BIO_DATAFIELD_DOC_RUN,
// BIO_DATAFIELD_DOC_NAMES,
// BIO_DATAFIELD_DOC_SURNAME_1,
// BIO_DATAFIELD_DOC_SURNAME_2,
// BIO_DATAFIELD_DOC_GENDER,

// ```
// /* Extendidos */
// BIO_DATAFIELD_DOC_NATIONALITY,
// BIO_DATAFIELD_DOC_MRZ,
// BIO_DATAFIELD_DOC_COUNTRY_OF_ISSUE,
// BIO_DATAFIELD_DOC_OCUPATION,
// BIO_DATAFIELD_DOC_BIRTHPLACE,
// BIO_DATAFIELD_DOC_ISSUEDATE,

// /* Biométricos */
// BIO_DATAFIELD_DOC_FACE,
// BIO_DATAFIELD_DOC_SIGNATURE,

// /* Fingerprint */
// BIO_DATAFIELD_DOC_FINGERID_1,
// BIO_DATAFIELD_DOC_FINGERID_2,
// BIO_DATAFIELD_DOC_FINGERID_1_TRIES_LEFT,
// BIO_DATAFIELD_DOC_FINGERID_2_TRIES_LEFT,

// /* ICAO DGs */
// BIO_DATAFIELD_DOC_DG_COM,
// BIO_DATAFIELD_DOC_DG_1,
// BIO_DATAFIELD_DOC_DG_2,
// BIO_DATAFIELD_DOC_DG_3,
// BIO_DATAFIELD_DOC_DG_4,
// BIO_DATAFIELD_DOC_DG_5,
// BIO_DATAFIELD_DOC_DG_6,
// BIO_DATAFIELD_DOC_DG_7,
// BIO_DATAFIELD_DOC_DG_8,
// BIO_DATAFIELD_DOC_DG_9,
// BIO_DATAFIELD_DOC_DG_10,
// BIO_DATAFIELD_DOC_DG_11,
// BIO_DATAFIELD_DOC_DG_12,
// BIO_DATAFIELD_DOC_DG_13,
// BIO_DATAFIELD_DOC_DG_14,
// BIO_DATAFIELD_DOC_DG_15
// ```

// };

// /* ============================================================
// BIO - ERRORES
// ============================================================ */

// enum BIO_ERROR
// {
// BIO_ERROR_NO_ERROR = 0,
// BIO_ERROR_NO_DATA_AVAILABLE
// };

// /* ============================================================
// BIO - DOCUMENT TYPES
// ============================================================ */

// enum BIO_DOCTYPE
// {
// BIO_DOCTYPE_CLID2013 = 0,
// BIO_DOCTYPE_CLID2013_ESP
// };

// /* ============================================================
// BIO - PROPERTIES
// ============================================================ */

// enum BIO_DATAFIELDPROP
// {
// BIO_DATAFIELDPROP_NONE = 0,
// BIO_DATAFIELDPROP_IMAGEFORMAT_SOLJP2
// };







#endif