#ifndef __BIO_DEFS__
#define __BIO_DEFS__

#include <stdio.h>

enum //SOLEMICAO_ERROR
{
    SOLEMICAO_ERROR_NO_ERROR = 0,

    SOLEMICAO_ERROR_TRANSMIT_PLAIN_APDU,
    SOLEMICAO_ERROR_TRANSMIT_PLAIN_APDU_RESP,

    SOLEMICAO_ERROR_TRANSMIT_SECURE_APDU,
    SOLEMICAO_ERROR_TRANSMIT_SECURE_APDU_DO87_ENC,
    SOLEMICAO_ERROR_TRANSMIT_SECURE_APDU_DO8E_MAC,
    SOLEMICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO99,
    SOLEMICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO8E,
    SOLEMICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO8E_MAC,
    SOLEMICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO8E_MAC_MISMATCH,
    SOLEMICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO87_DENC,

    SOLEMICAO_ERROR_GETMAC_ENCRYPT,
    SOLEMICAO_ERROR_GETMAC_DECRYPT,

    SOLEMICAO_ERROR_UPDATEKEY_GETDOCBARCODE,
    SOLEMICAO_ERROR_UPDATEKEY_GETDOCTYPE,
    SOLEMICAO_ERROR_UPDATEKEY_INVALID_DOCTYPE,
    SOLEMICAO_ERROR_UPDATEKEY_GETDOCSERIAL,
    SOLEMICAO_ERROR_UPDATEKEY_DOCSERIAL_UNAVAILABLE,
    SOLEMICAO_ERROR_UPDATEKEY_GETDOCBIRTHDATE,
    SOLEMICAO_ERROR_UPDATEKEY_DOCBIRTHDATE_UNAVAILABLE,
    SOLEMICAO_ERROR_UPDATEKEY_GETDOCEXPIRYDATE,
    SOLEMICAO_ERROR_UPDATEKEY_DOCEXPIRYDATE_UNAVAILABLE,

    SOLEMICAO_ERROR_AUTHENTICATE,
    SOLEMICAO_ERROR_AUTHENTICATE_RESP,

    SOLEMICAO_ERROR_UPDATEICAORESULTS_PUTDATA_DOC_BIRTHDATE,
    SOLEMICAO_ERROR_AUTHENTICATE_KSEED_HASH,
    SOLEMICAO_ERROR_AUTHENTICATE_KENC_HASH,
    SOLEMICAO_ERROR_AUTHENTICATE_KMAC_HASH,
    SOLEMICAO_ERROR_AUTHENTICATE_LOCAL_CHALLENGE,
    SOLEMICAO_ERROR_AUTHENTICATE_LOCAL_RAND,
    SOLEMICAO_ERROR_AUTHENTICATE_AUTH_DATA_ENC,
    SOLEMICAO_ERROR_AUTHENTICATE_AUTH_DATA_MAC,
    SOLEMICAO_ERROR_AUTHENTICATE_RESP_LEN,
    SOLEMICAO_ERROR_AUTHENTICATE_RESP_DATA_MAC,
    SOLEMICAO_ERROR_AUTHENTICATE_RESP_MAC_VERIFICATION,
    SOLEMICAO_ERROR_AUTHENTICATE_RESP_DATA_ENC,
    SOLEMICAO_ERROR_AUTHENTICATE_RESP_SCARD_CHALLENGE_VERIFICATION,
    SOLEMICAO_ERROR_AUTHENTICATE_RESP_LOCAL_CHALLENGE_VERIFICATION,


    SOLEMICAO_ERROR_UPDATEICAORESULTS_DATAFIELD_INALID,
    SOLEMICAO_ERROR_CONNETC_SELECT_DIR,
    SOLEMICAO_ERROR_CONNETC_SELECT_DIR_RESP,

    SOLEMICAO_ERROR_GETFINGERREF_PUTDATA_FINGER1,
    SOLEMICAO_ERROR_GETDOCUMENTNUMBER_SELECT_APP,
    SOLEMICAO_ERROR_GETDOCUMENTNUMBER_SELECT_APP_RESP,
    SOLEMICAO_ERROR_GETDOCUMENTNUMBER_SELECT_MF,
    SOLEMICAO_ERROR_GETDOCUMENTNUMBER_SELECT_MF_RESP,
    SOLEMICAO_ERROR_GETDOCUMENTNUMBER_SELECT,
    SOLEMICAO_ERROR_GETDOCUMENTNUMBER_SELECT_RESP,
    SOLEMICAO_ERROR_GETDOCUMENTNUMBER_READ,
    SOLEMICAO_ERROR_GETDOCUMENTNUMBER_READ_RESP,


    SOLEMICAO_ERROR_CONNETC_WRAP,
    SOLEMICAO_ERROR_CONNETC_READ_BIN,
    SOLEMICAO_ERROR_CONNETC_READ_BIN_RESP,
    SOLEMICAO_ERROR_CONNETC_PACE_SEC_NEW,
    SOLEMICAO_ERROR_CONNETC_EAC_INIT_CTX,
    SOLEMICAO_ERROR_CONNETC_PACE_STEP2,
    SOLEMICAO_ERROR_CONNETC_PACE_STEP3A,
    SOLEMICAO_ERROR_CONNETC_UNWRAP,
    SOLEMICAO_ERROR_CONNETC_PACE_STEP3A_MAP,
    SOLEMICAO_ERROR_CONNETC_PACE_STEP3B,
    SOLEMICAO_ERROR_CONNETC_BUFF_MEM_INIT,
    SOLEMICAO_ERROR_CONNETC_PACE_STEP3C,
    SOLEMICAO_ERROR_CONNETC_PACE_STEP3D,
    SOLEMICAO_ERROR_CONNETC_PACE_STEP3D_VERIF,
    SOLEMICAO_ERROR_CONNETC_EAC_SET_CTX,
    SOLEMICAO_ERROR_GETFINGERREF_SELECT_APP,
    SOLEMICAO_ERROR_GETFINGERREF_SELECT_APP_RESP,
    SOLEMICAO_ERROR_GETICAO_SELECT_APP,
    SOLEMICAO_ERROR_GETICAO_SELECT_APP_RESP,
    SOLEMICAO_ERROR_GETICAO_GETCHALLENGE,
    SOLEMICAO_ERROR_GETICAO_GETCHALLENGE_RESP,
    SOLEMICAO_ERROR_GETICAO_GETCHALLENGE_RESP_LEN,
    SOLEMICAO_ERROR_GETICAO_AUTHENTICATE,
    SOLEMICAO_ERROR_GETICAO_SELECTDG,
    SOLEMICAO_ERROR_GETICAO_SELECTDG_RESP,
    SOLEMICAO_ERROR_GETICAO_READDG,
    SOLEMICAO_ERROR_GETICAO_READDG_RESP,
    SOLEMICAO_ERROR_GETICAO_READDG_RESP_LEN,
    SOLEMICAO_ERROR_GETICAO_READDG_OVERFLOW,
    SOLEMICAO_ERROR_GETFINGERREF_GETDATA1,
    SOLEMICAO_ERROR_GETFINGERREF_GETDATA1_RESP,
    SOLEMICAO_ERROR_GETFINGERREF_PUTDATA_FINGER2,
    SOLEMICAO_ERROR_GETDOCUMENTNUMBER_PUTDATA_DOC_SERIAL,
    SOLEMICAO_ERROR_INIT_ENGINEHANDLE_MEM,
    SOLEMICAO_ERROR_CREATE_MUTEX,

    SOLEMICAO_ERROR_ADDCAPTUREFIELD_DATAFIELD_INALID,
    SOLEMICAO_ERROR_CAPTURE_DEVICEHANDLE_NULL,

SOLEMICAO_ERROR_CAPTURE_GETCARD,
SOLEMICAO_ERROR_CAPTURE_DISCONNECT,
SOLEMICAO_ERROR_MOC_DEVICEHANDLE_NULL,
SOLEMICAO_ERROR_MOC_FINGER_REF_INVALID,
SOLEMICAO_ERROR_MOC_GET_TEMPLATE,
SOLEMICAO_ERROR_NO_CARD_AVAILABLE,
SOLEMICAO_ERROR_MOC_GETCARD,
SOLEMICAO_ERROR_MOC_SELECT_APP_RESP,
SOLEMICAO_ERROR_MOC_MATCH,
SOLEMICAO_ERROR_MOC_SELECT_APP,
SOLEMICAO_ERROR_MOC_MATCH_P1,
SOLEMICAO_ERROR_MOC_MATCH_WRONG_LENGTH,
SOLEMICAO_ERROR_MOC_MATCH_PIN_NOT_FOUND,
SOLEMICAO_ERROR_MOC_MATCH_SECURITY,
SOLEMICAO_ERROR_MOC_MATCH_COUNTER_ZERO,
SOLEMICAO_ERROR_MOC_MATCH_NEED_MORE_DATA,
SOLEMICAO_ERROR_MOC_MATCH_UNKNOWN,
SOLEMICAO_ERROR_MOC_DISCONNECT,




};

enum // SOLEMBIO_DATAFIELD
{
    SOLEMBIO_MOC_HIT = 0,
    SOLEMBIO_MOC_NOHIT
};



enum // SOLEMBIO_DATAFIELD
{
    SOLEMBIO_DATAFIELD_DOC_BARCODE = 0,
    SOLEMBIO_DATAFIELD_DOC_TYPE,
    SOLEMBIO_DATAFIELD_DOC_SERIAL,
    SOLEMBIO_DATAFIELD_DOC_BIRTHDATE,
    SOLEMBIO_DATAFIELD_DOC_EXPIRYDATE,
    SOLEMBIO_DATAFIELD_DOC_RUN,
    SOLEMBIO_DATAFIELD_DOC_NAMES,
    SOLEMBIO_DATAFIELD_DOC_SURNAME_1,
    SOLEMBIO_DATAFIELD_DOC_SURNAME_2,
    SOLEMBIO_DATAFIELD_DOC_GENDER,

    SOLEMBIO_DATAFIELD_DOC_NATIONALITY,
    SOLEMBIO_DATAFIELD_DOC_MRZ,
    SOLEMBIO_DATAFIELD_DOC_COUNTRY_OF_ISSUE,
    SOLEMBIO_DATAFIELD_DOC_OCUPATION,
    SOLEMBIO_DATAFIELD_DOC_BIRTHPLACE,
    SOLEMBIO_DATAFIELD_DOC_ISSUEDATE,

    SOLEMBIO_DATAFIELD_DOC_FACE,
    SOLEMBIO_DATAFIELD_DOC_SIGNATURE,

    SOLEMBIO_DATAFIELD_DOC_FINGERID_1,
    SOLEMBIO_DATAFIELD_DOC_FINGERID_2,
    SOLEMBIO_DATAFIELD_DOC_FINGERID_1_TRIES_LEFT,
    SOLEMBIO_DATAFIELD_DOC_FINGERID_2_TRIES_LEFT,

    SOLEMBIO_DATAFIELD_DOC_DG_COM,
    SOLEMBIO_DATAFIELD_DOC_DG_1,
    SOLEMBIO_DATAFIELD_DOC_DG_2,
    SOLEMBIO_DATAFIELD_DOC_DG_3,
    SOLEMBIO_DATAFIELD_DOC_DG_4,
    SOLEMBIO_DATAFIELD_DOC_DG_5,
    SOLEMBIO_DATAFIELD_DOC_DG_6,
    SOLEMBIO_DATAFIELD_DOC_DG_7,
    SOLEMBIO_DATAFIELD_DOC_DG_8,
    SOLEMBIO_DATAFIELD_DOC_DG_9,
    SOLEMBIO_DATAFIELD_DOC_DG_10,
    SOLEMBIO_DATAFIELD_DOC_DG_11,
    SOLEMBIO_DATAFIELD_DOC_DG_12,
    SOLEMBIO_DATAFIELD_DOC_DG_13,
    SOLEMBIO_DATAFIELD_DOC_DG_14,
    SOLEMBIO_DATAFIELD_DOC_DG_15,

    SOLEMBIO_DATAFIELDPROP_NONE,

    SOLEMBIO_DATAFIELDPROP_IMAGEFORMAT_SOLJP2,

    SOLEMBIO_DATAFIELDPROP_MINUTIAE_SOLISOC,

    SOLEMBIO_FINGER_NONE

};


enum {
    SCL_FNBITMAP_ON = 0
};


enum {
    SOLEMBIO_ERROR_NO_ERROR = 0,
    SOLEMBIO_ERROR_NO_DATA_AVAILABLE,
    SOLEMBIO_ERROR_LICENSE_FNBITMAP_OFF,
    SOLEMBIO_ERROR_MOC_LOCKED
};


enum {
    SOLEMBIO_DOCTYPE_CLID2013 = 0,
    SOLEMBIO_DOCTYPE_CLID2013_ESP,
    SOLEMBIO_FEATUREBITMAP_CAPT_ICAO_DATA,
    SOLEMBIO_FEATUREBITMAP_CAPT_ICAO_FACE,
    SOLEMBIO_FEATUREBITMAP_CAPT_ICAO_SIGNATURE,
    SOLEMBIO_FEATUREBITMAP_CAPT_ICAO_DOCNUM,
    SOLEMBIO_FEATUREBITMAP_CAPT_ICAO_FINGER,
    SOLEMBIO_FEATUREBITMAP_CAPT_ICAO_DATAGROUP
    
};

enum {
    SOLEMBIO_DEVICE_BIOPIN = 0,
    SOLEMBIO_DEVICE_BCR250BT,
    SOLEMBIO_DEVICE_NFC
};


enum {
    SMARTCARD_ERROR_NO_ERROR = 0,
    SMARTCARD_ERROR_NO_CARD_AVAILABLE
};


// enum  enDataField
// {
//     SMARTCARD_ERROR_NO_ERROR = 0,
//     SMARTCARD_ERROR_NO_CARD_AVAILABLE
// };







// #ifndef SOLEM_ENUMS_H
// #define SOLEM_ENUMS_H

// /* ============================================================
// SOLEMICAO - ERRORES
// ============================================================ */

// enum SOLEMICAO_ERROR
// {
// SOLEMICAO_ERROR_NO_ERROR = 0,

// ```
// /* Plain APDU */
// SOLEMICAO_ERROR_TRANSMIT_PLAIN_APDU,
// SOLEMICAO_ERROR_TRANSMIT_PLAIN_APDU_RESP,

// /* Secure APDU */
// SOLEMICAO_ERROR_TRANSMIT_SECURE_APDU,
// SOLEMICAO_ERROR_TRANSMIT_SECURE_APDU_DO87_ENC,
// SOLEMICAO_ERROR_TRANSMIT_SECURE_APDU_DO8E_MAC,
// SOLEMICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO99,
// SOLEMICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO8E,
// SOLEMICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO8E_MAC,
// SOLEMICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO8E_MAC_MISMATCH,
// SOLEMICAO_ERROR_TRANSMIT_SECURE_APDURESP_DO87_DENC,

// /* MAC / Crypto */
// SOLEMICAO_ERROR_GETMAC_ENCRYPT,
// SOLEMICAO_ERROR_GETMAC_DECRYPT,

// /* Update ICAO Key */
// SOLEMICAO_ERROR_UPDATEKEY_GETDOCBARCODE,
// SOLEMICAO_ERROR_UPDATEKEY_GETDOCTYPE,
// SOLEMICAO_ERROR_UPDATEKEY_INVALID_DOCTYPE,
// SOLEMICAO_ERROR_UPDATEKEY_GETDOCSERIAL,
// SOLEMICAO_ERROR_UPDATEKEY_DOCSERIAL_UNAVAILABLE,
// SOLEMICAO_ERROR_UPDATEKEY_GETDOCBIRTHDATE,
// SOLEMICAO_ERROR_UPDATEKEY_DOCBIRTHDATE_UNAVAILABLE,
// SOLEMICAO_ERROR_UPDATEKEY_GETDOCEXPIRYDATE,
// SOLEMICAO_ERROR_UPDATEKEY_DOCEXPIRYDATE_UNAVAILABLE,

// /* Update ICAO Results */
// SOLEMICAO_ERROR_UPDATEICAORESULTS_PUTDATA_DOC_BIRTHDATE,
// SOLEMICAO_ERROR_UPDATEICAORESULTS_DATAFIELD_INALID,

// /* Authentication */
// SOLEMICAO_ERROR_AUTHENTICATE_KSEED_HASH,
// SOLEMICAO_ERROR_AUTHENTICATE_KENC_HASH,
// SOLEMICAO_ERROR_AUTHENTICATE_KMAC_HASH,
// SOLEMICAO_ERROR_AUTHENTICATE_LOCAL_CHALLENGE,
// SOLEMICAO_ERROR_AUTHENTICATE_LOCAL_RAND,
// SOLEMICAO_ERROR_AUTHENTICATE_AUTH_DATA_ENC,
// SOLEMICAO_ERROR_AUTHENTICATE_AUTH_DATA_MAC,
// SOLEMICAO_ERROR_AUTHENTICATE,
// SOLEMICAO_ERROR_AUTHENTICATE_RESP,
// SOLEMICAO_ERROR_AUTHENTICATE_RESP_LEN,
// SOLEMICAO_ERROR_AUTHENTICATE_RESP_DATA_MAC,
// SOLEMICAO_ERROR_AUTHENTICATE_RESP_MAC_VERIFICATION,
// SOLEMICAO_ERROR_AUTHENTICATE_RESP_DATA_ENC,
// SOLEMICAO_ERROR_AUTHENTICATE_RESP_SCARD_CHALLENGE_VERIFICATION,
// SOLEMICAO_ERROR_AUTHENTICATE_RESP_LOCAL_CHALLENGE_VERIFICATION,

// /* Connect / NFC */
// SOLEMICAO_ERROR_CONNETC_SELECT_DIR,
// SOLEMICAO_ERROR_CONNETC_SELECT_DIR_RESP,
// SOLEMICAO_ERROR_CONNETC_WRAP,
// SOLEMICAO_ERROR_CONNETC_READ_BIN
// ```

// };

// /* ============================================================
// SOLEMBIO - DATA FIELDS (COMPLETO)
// ============================================================ */

// enum SOLEMBIO_DATAFIELD
// {
// /* Básicos */
// SOLEMBIO_DATAFIELD_DOC_BARCODE = 0,
// SOLEMBIO_DATAFIELD_DOC_TYPE,
// SOLEMBIO_DATAFIELD_DOC_SERIAL,
// SOLEMBIO_DATAFIELD_DOC_BIRTHDATE,
// SOLEMBIO_DATAFIELD_DOC_EXPIRYDATE,
// SOLEMBIO_DATAFIELD_DOC_RUN,
// SOLEMBIO_DATAFIELD_DOC_NAMES,
// SOLEMBIO_DATAFIELD_DOC_SURNAME_1,
// SOLEMBIO_DATAFIELD_DOC_SURNAME_2,
// SOLEMBIO_DATAFIELD_DOC_GENDER,

// ```
// /* Extendidos */
// SOLEMBIO_DATAFIELD_DOC_NATIONALITY,
// SOLEMBIO_DATAFIELD_DOC_MRZ,
// SOLEMBIO_DATAFIELD_DOC_COUNTRY_OF_ISSUE,
// SOLEMBIO_DATAFIELD_DOC_OCUPATION,
// SOLEMBIO_DATAFIELD_DOC_BIRTHPLACE,
// SOLEMBIO_DATAFIELD_DOC_ISSUEDATE,

// /* Biométricos */
// SOLEMBIO_DATAFIELD_DOC_FACE,
// SOLEMBIO_DATAFIELD_DOC_SIGNATURE,

// /* Fingerprint */
// SOLEMBIO_DATAFIELD_DOC_FINGERID_1,
// SOLEMBIO_DATAFIELD_DOC_FINGERID_2,
// SOLEMBIO_DATAFIELD_DOC_FINGERID_1_TRIES_LEFT,
// SOLEMBIO_DATAFIELD_DOC_FINGERID_2_TRIES_LEFT,

// /* ICAO DGs */
// SOLEMBIO_DATAFIELD_DOC_DG_COM,
// SOLEMBIO_DATAFIELD_DOC_DG_1,
// SOLEMBIO_DATAFIELD_DOC_DG_2,
// SOLEMBIO_DATAFIELD_DOC_DG_3,
// SOLEMBIO_DATAFIELD_DOC_DG_4,
// SOLEMBIO_DATAFIELD_DOC_DG_5,
// SOLEMBIO_DATAFIELD_DOC_DG_6,
// SOLEMBIO_DATAFIELD_DOC_DG_7,
// SOLEMBIO_DATAFIELD_DOC_DG_8,
// SOLEMBIO_DATAFIELD_DOC_DG_9,
// SOLEMBIO_DATAFIELD_DOC_DG_10,
// SOLEMBIO_DATAFIELD_DOC_DG_11,
// SOLEMBIO_DATAFIELD_DOC_DG_12,
// SOLEMBIO_DATAFIELD_DOC_DG_13,
// SOLEMBIO_DATAFIELD_DOC_DG_14,
// SOLEMBIO_DATAFIELD_DOC_DG_15
// ```

// };

// /* ============================================================
// SOLEMBIO - ERRORES
// ============================================================ */

// enum SOLEMBIO_ERROR
// {
// SOLEMBIO_ERROR_NO_ERROR = 0,
// SOLEMBIO_ERROR_NO_DATA_AVAILABLE
// };

// /* ============================================================
// SOLEMBIO - DOCUMENT TYPES
// ============================================================ */

// enum SOLEMBIO_DOCTYPE
// {
// SOLEMBIO_DOCTYPE_CLID2013 = 0,
// SOLEMBIO_DOCTYPE_CLID2013_ESP
// };

// /* ============================================================
// SOLEMBIO - PROPERTIES
// ============================================================ */

// enum SOLEMBIO_DATAFIELDPROP
// {
// SOLEMBIO_DATAFIELDPROP_NONE = 0,
// SOLEMBIO_DATAFIELDPROP_IMAGEFORMAT_SOLJP2
// };







#endif